/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.sesap.Interface;

import com.mycompany.sesap.Capturas.CapturaeEnviodeEmail;
import com.mycompany.sesap.POO.Curriculo;
import com.mycompany.sesap.dao.CurriculoDAO;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.commons.mail.EmailException;


/**
 *
 * @author Erick
 */
public class Interface extends javax.swing.JDialog {
    File arq;
    String caminho;

    /**
     * Creates new form Interface
     */
    public Interface(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        aSQAs = new javax.swing.JLabel();
        tele = new javax.swing.JLabel();
        Camp_Escolaridade = new javax.swing.JLabel();
        Camp_Nome4 = new javax.swing.JLabel();
        Camp_Nome5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Camp_Nome = new javax.swing.JTextField();
        Camp_Email = new javax.swing.JTextField();
        Camp_Telefone = new javax.swing.JTextField();
        Camp_Cargo = new javax.swing.JTextField();
        Camp_OBS = new javax.swing.JTextField();
        Box_Escolaridade = new javax.swing.JComboBox<>();
        BT_Anexar = new javax.swing.JButton();
        BT_Enviar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cargo Desejado:");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome completo:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefone:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-Mail:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        Nome.setBackground(new java.awt.Color(255, 255, 255));
        Nome.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        Nome.setForeground(new java.awt.Color(255, 255, 255));
        Nome.setText("Nome completo:*");

        aSQAs.setBackground(new java.awt.Color(255, 255, 255));
        aSQAs.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        aSQAs.setForeground(new java.awt.Color(255, 255, 255));
        aSQAs.setText("E-Mail:*");

        tele.setBackground(new java.awt.Color(255, 255, 255));
        tele.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        tele.setForeground(new java.awt.Color(255, 255, 255));
        tele.setText("Telefone:*");

        Camp_Escolaridade.setBackground(new java.awt.Color(255, 255, 255));
        Camp_Escolaridade.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        Camp_Escolaridade.setForeground(new java.awt.Color(255, 255, 255));
        Camp_Escolaridade.setText("Escolaridade:*");

        Camp_Nome4.setBackground(new java.awt.Color(255, 255, 255));
        Camp_Nome4.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        Camp_Nome4.setForeground(new java.awt.Color(255, 255, 255));
        Camp_Nome4.setText("Cargo Desejado:*");

        Camp_Nome5.setBackground(new java.awt.Color(255, 255, 255));
        Camp_Nome5.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        Camp_Nome5.setForeground(new java.awt.Color(255, 255, 255));
        Camp_Nome5.setText("Observaçoes:");

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Arquivo:*");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Camp_Nome.setBackground(new java.awt.Color(255, 255, 255));
        Camp_Nome.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        Camp_Email.setBackground(new java.awt.Color(255, 255, 255));
        Camp_Email.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        Camp_Telefone.setBackground(new java.awt.Color(255, 255, 255));
        Camp_Telefone.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        Camp_Cargo.setBackground(new java.awt.Color(255, 255, 255));
        Camp_Cargo.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        Camp_OBS.setBackground(new java.awt.Color(255, 255, 255));
        Camp_OBS.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        Box_Escolaridade.setBackground(new java.awt.Color(255, 255, 255));
        Box_Escolaridade.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Box_Escolaridade.setForeground(new java.awt.Color(0, 0, 0));
        Box_Escolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensino Medio", "Superior", "Doutorado", "Pós Graduaçao" }));

        BT_Anexar.setBackground(new java.awt.Color(255, 255, 255));
        BT_Anexar.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        BT_Anexar.setForeground(new java.awt.Color(0, 0, 0));
        BT_Anexar.setText("Anexar");
        BT_Anexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AnexarActionPerformed(evt);
            }
        });

        BT_Enviar.setBackground(new java.awt.Color(255, 255, 255));
        BT_Enviar.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        BT_Enviar.setForeground(new java.awt.Color(0, 0, 0));
        BT_Enviar.setText("Enviar");
        BT_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EnviarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PREENCHA COM SEUS DADOS PESSOAIS!");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aSQAs, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(tele, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(Camp_Nome4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Camp_Nome)
                            .addComponent(Camp_Email)
                            .addComponent(Camp_Telefone)
                            .addComponent(Camp_Cargo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Camp_Nome5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Camp_OBS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Camp_Escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box_Escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(167, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_Anexar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(BT_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(Camp_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Camp_Escolaridade)
                    .addComponent(Box_Escolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aSQAs)
                    .addComponent(Camp_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Camp_Nome5)
                        .addComponent(Camp_OBS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tele)
                            .addComponent(Camp_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Camp_Nome4)
                            .addComponent(Camp_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BT_Anexar))
                .addGap(50, 50, 50)
                .addComponent(BT_Enviar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_EnviarActionPerformed
       // Validando Todos os Campos do formulário
if (!camposFormularioValidos()) {
    return; // Se algum campo não for válido, sai do método
}

// Verificando se um arquivo foi anexado
if (arq == null || !arq.exists()) {
    JOptionPane.showMessageDialog(null, "Nenhum arquivo anexado.", "Arquivo não selecionado", JOptionPane.WARNING_MESSAGE);
    return;
}

// Verificando se o arquivo é válido
if (!isValidFile(arq.getAbsolutePath())) {
    JOptionPane.showMessageDialog(null, "Arquivo não está no formato permitido (.doc, .docx, .pdf) ou excede 1MB.", "Arquivo inválido", JOptionPane.WARNING_MESSAGE);
    return;
}

// Criando e preenchendo o objeto Curriculo
Curriculo c = new Curriculo();
c.setNome(Camp_Nome.getText());
c.setEmail(Camp_Email.getText());
c.setTelefone(Camp_Telefone.getText());
c.setCargoDesejado(Camp_Cargo.getText());
c.setEscolaridade(Box_Escolaridade.getSelectedItem().toString());
c.setObservaçoes(Camp_OBS.getText());
c.setArquivo(arq.getName());

if (c == null) {
    System.out.println("c é nulo após a criação do objeto Curriculo.");
    return;
} else {
    System.out.println("c não é nulo. Dados do objeto Curriculo:");
    System.out.println("Nome: " + c.getNome());
    System.out.println("Email: " + c.getEmail());
    System.out.println("Telefone: " + c.getTelefone());
    System.out.println("Cargo Desejado: " + c.getCargoDesejado());
    System.out.println("Escolaridade: " + c.getEscolaridade());
    System.out.println("Observaçoes: " + c.getObservaçoes());
    System.out.println("Arquivo: " + c.getArquivo());
}

// Tentando salvar no banco de dados
try {
    CurriculoDAO cdao = new CurriculoDAO();
    cdao.inserir(c);
    System.out.println("Dados salvos no banco de dados com sucesso!");

    // Enviando email com o currículo anexado
    CapturaeEnviodeEmail emailSender = new CapturaeEnviodeEmail();
    emailSender.enviar(arq.getPath(), arq.getName(), arq.getPath(), c);
    System.out.println("Email enviado com sucesso!");

} catch (Exception e) {
    
}
}

// Método para validar todos os campos
private boolean camposFormularioValidos() {
    if (Camp_Nome.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo nome obrigatório!", "Preencha com seu nome!", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    if (Camp_Email.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo E-Mail obrigatório!", "Preencha com seu E-Mail!", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    if (Camp_Telefone.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Telefone obrigatório!", "Preencha com seu Telefone!", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    if (Camp_Cargo.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Cargo obrigatório!", "Preencha com seu Cargo!", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    if (Box_Escolaridade.getSelectedItem().toString().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Escolaridade obrigatório!", "Preencha com sua Escolaridade!", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    return true;
}

    // Método para validar o arquivo
    private boolean isValidFile(String caminho) {
    File file = new File(caminho);

    // Verifica se o arquivo existe
    if (!file.exists() || !file.isFile()) {
        System.err.println("O arquivo não existe ou não é um arquivo válido.");
        return false;
    }

    // Verifica o tamanho do arquivo
    long MAX_FILE_SIZE_BYTES = 1 * 1024 * 1024; // 1MB
    if (file.length() > MAX_FILE_SIZE_BYTES) {
        System.err.println("O arquivo excede o tamanho máximo permitido de 1MB.");
        return false;
    }

    // Verifica a extensão do arquivo
    String fileName = file.getName().toLowerCase();
    if (!(fileName.endsWith(".doc") || fileName.endsWith(".docx") || fileName.endsWith(".pdf"))) {
        System.err.println("O arquivo não é do tipo permitido. Permitidos: .doc, .docx, .pdf.");
        return false;
    }

    return true;
    }//GEN-LAST:event_BT_EnviarActionPerformed

    private void BT_AnexarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AnexarActionPerformed
        //criando o chooser e executando ao pressionar BT
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        
        arq = chooser.getSelectedFile().getAbsoluteFile();
        caminho = arq.getAbsolutePath();
       
    }//GEN-LAST:event_BT_AnexarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Interface dialog = new Interface(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Anexar;
    private javax.swing.JButton BT_Enviar;
    private javax.swing.JComboBox<String> Box_Escolaridade;
    private javax.swing.JTextField Camp_Cargo;
    private javax.swing.JTextField Camp_Email;
    private javax.swing.JLabel Camp_Escolaridade;
    private javax.swing.JTextField Camp_Nome;
    private javax.swing.JLabel Camp_Nome4;
    private javax.swing.JLabel Camp_Nome5;
    private javax.swing.JTextField Camp_OBS;
    private javax.swing.JTextField Camp_Telefone;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel aSQAs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tele;
    // End of variables declaration//GEN-END:variables

}
